Openlibrary integration
wolox-training/am-rails pull request #23
Opened 2018-10-04 22:18 UTC by aleochoam

### Summary
- Added the gem httparty
- Created the OpenLibraryService to integrate with OpenLibrary API
- Created the OpenLibrary controller 

### Trello Card
https://trello.com/c/U8SeNreV/36-integraci%C3%B3n-api-externa

2018-10-05 17:43 UTC, Gmarn requested changes

2018-10-05 17:43 UTC, Gmarn commented on config/routes.rb
> +    resources :info, only: :show, controller: :open_library
Here, you do not have the resource `info`. You have 2 betters option:
1. use the resource books (seems logic because we will return book info) but with a custom get.
2. create a basic endpoint without resource.

I prefer `1`

2018-10-05 17:43 UTC, Gmarn commented on app/controllers/api/v1/open_library_controller.rb
> +        book = OpenLibraryService.new.book_info params[:id]
`:id` this is reserve for record you have in your DB, here I would prefer: `:isbn` for example.

2018-10-05 17:43 UTC, Gmarn commented on app/controllers/api/v1/open_library_controller.rb
> +        render json: book
And what happen when the external API does not return a book? How do you handle errors?

2018-10-05 17:43 UTC, Gmarn commented on app/services/open_library_service.rb
> +  base_uri 'openlibrary.org/api/books'
Usualy we use `secrets.yml` to store this type of variable, also could be add to your `.env`

2018-10-05 17:43 UTC, Gmarn commented on app/services/open_library_service.rb
> +        bibkeys: isbn,
Why not using the power of the class an use `initialize` method to define this?

2018-10-05 17:43 UTC, Gmarn commented on app/services/open_library_service.rb
> +    }
I prefer encapsulated this in an independent method and let this method only for the `get`

2018-10-05 17:43 UTC, Gmarn commented on app/services/open_library_service.rb
> +        format: 'json',
When introducing pure variable as this is better to define it at the top of the class:
```
FORMAT = 'json'.freeze
```

2018-10-05 17:43 UTC, Gmarn commented on app/services/open_library_service.rb
> +        jscmd: 'data'
same

2018-10-08 17:05 UTC, Gmarn requested changes

2018-10-08 17:05 UTC, Gmarn commented on app/services/open_library_service.rb
> +  # Keys
It's a good idea, but keys are no variable, you can call them directly, without defining them here.

2018-10-08 17:05 UTC, Gmarn commented on app/services/open_library_service.rb
> +    raise "No book found with code #{@isbn}" if response.body == '{}'
Ok, and where did you rescue this error?
Also I prefer you handle the choice of response in the controller, than the service.

2018-10-08 17:05 UTC, Gmarn commented on app/services/open_library_service.rb
> +  def format_response(response)
Why not receive directly `response[@isbn]` here?

2018-10-08 19:46 UTC, aleochoam commented on app/services/open_library_service.rb
> +    raise "No book found with code #{@isbn}" if response.body == '{}'
I rescue the error in the controller. You mean not raising an error and, in the controller, do the check for emptiness?

2018-10-09 13:06 UTC, Gmarn requested changes

2018-10-09 13:06 UTC, Gmarn commented on config/routes.rb
> +        get 'info'
My bad, I did the error on the comment before, but better tu use symbol here: `:info`

2018-10-09 13:06 UTC, Gmarn commented on app/services/open_library_service.rb
> +    raise "No book found with code #{@isbn}" if response.body == '{}'
Sorry maybe I missed something, but I do not see were you rescue this in the controller. If you want we speak about it on slack.

2018-10-09 14:09 UTC, Gmarn requested changes

2018-10-09 14:09 UTC, Gmarn commented on app/controllers/api/v1/books_controller.rb
> +        if book == {}
Prefer using ruby function as: `book.empty?`

2018-10-09 14:09 UTC, Gmarn commented on app/controllers/api/v1/books_controller.rb
> +          render json: { error: "No book found with code #{isbn}" }
Can you try to internationalize you error message?

2018-10-09 14:09 UTC, Gmarn commented on app/controllers/api/v1/books_controller.rb
> +        end
Maybe you can avoid this if / else / end structure and did something like line 16?

2018-10-09 14:09 UTC, Gmarn commented on app/services/open_library_service.rb
> +    return {} if response.nil?
Very good 👍

2018-10-09 18:01 UTC, Gmarn approved these changes

2018-10-09 18:01 UTC, Gmarn commented on app/controllers/api/v1/books_controller.rb
> +        return render json: { error: t('.no_book_error', code: isbn) } if book_info.empty?
You missed `status: :not_found` or `bad_request`

2018-10-09 18:19 UTC, merged