Send rent expiry email
wolox-training/am-rails pull request #26
Opened 2018-10-08 14:27 UTC by aleochoam

### Summary
- Added the gem sidekiq-scheduler
- Created the job for seeking the expiring rents and mail each one
- Settting the current time zone (Buenos Aires)
- Added the I18n translations and the layouts for the email
- Cron the job to be executed at 9:00 everyday

2018-10-08 18:11 UTC, Gmarn requested changes

2018-10-08 18:11 UTC, Gmarn commented on app/mailers/rent_mailer.rb
> +    rent_id = params[:rent_id]
This line is not very useful.

2018-10-08 18:11 UTC, Gmarn commented on app/mailers/rent_mailer.rb
> +    @rent = Rent.find(rent_id)
You could put this in a method with memorization
```ruby
def rent
  @rent ||= Rent.find(params[:rent_id]
end
```
And call it in this mailer method and the one above.

2018-10-08 18:11 UTC, Gmarn commented on config/application.rb
> +    config.time_zone = 'Buenos Aires'
Better to not change this for all you app, but only on your cron.

2018-10-08 18:11 UTC, Gmarn commented on config/sidekiq.yml
> +    cron: '0 9 * * *'
You can define it directly here, as ths example:
`cron: '0 0 * * * America/Santiago'`

Or [Here](https://stackoverflow.com/questions/13289751/cron-job-in-a-different-timezone) there is some more help.

2018-10-08 18:11 UTC, Gmarn commented on app/views/rent_mailer/rent_expiry.html.slim
> +  = t('.title' , title: @book.title)
It's strange, that you repeat the `title` here...

2018-10-08 18:11 UTC, Gmarn commented on app/jobs/rent_validation_job.rb
> +class RentValidationJob < ApplicationJob
We prefer use `/app/workers/` folder at wolox. Also you can delete `ApplicationJob`, no usefull here

2018-10-08 18:11 UTC, Gmarn commented on app/jobs/rent_validation_job.rb
> +class RentValidationJob < ApplicationJob
And we name workers as: `RentValidationWorker`

2018-10-08 20:25 UTC, aleochoam commented on app/views/rent_mailer/rent_expiry.html.slim
> +  = t('.title' , title: @book.title)
What do you mean by 'repeat'?

2018-10-09 13:16 UTC, Gmarn approved these changes

2018-10-09 13:16 UTC, Gmarn commented on app/views/rent_mailer/rent_expiry.html.slim
> +  = t('.title' , title: @book.title)
You ever put this on the subject of the mail, so it seems strange to me that you repeat it here.

2018-10-09 18:24 UTC, merged